#ifndef _SMART_H_
#define _SMART_H_

/****************/
/* Field Length */
/****************/
// 0. Appendage List
uint64_t APPEND_ELEMENT_LENGTH_LEN = 1;
uint64_t APPEND_FORMATCODE_LEN = 1;
uint64_t APPEND_VALUETYPECODE_LEN = 1;

// 1. System Event
uint64_t SYSTEM_EVENT_MSG_TYPE_LEN = 1;
uint64_t SYSTEM_EVENT_TIMESTAMP_LEN = 8;
uint64_t SYSTEM_EVENT_EVENTCODE_LEN = 4;

// 2. Channel Seconds
uint64_t CHANNEL_SECONDS_MSG_TYPE_LEN = 1;
uint64_t CHANNEL_SECONDS_PROTOCOL_ID_LEN = 1;
uint64_t CHANNEL_SECONDS_CHANNEL_INDEX_LEN = 1;
uint64_t CHANNEL_SECONDS_SECONDS_LEN = 4;

// 3. Market Center Locate
uint64_t MARKET_CENTER_LOCATE_MSG_TYPE_LEN = 1;
uint64_t MARKET_CENTER_LOCATE_LOCATECODE_LEN = 2;
uint64_t MARKET_CENTER_LOCATE_MIC_LEN = 4;

// 4. Instrument Locate
uint64_t INSTRUMENT_LOCATE_MSG_TYPE_LEN = 1;
uint64_t INSTRUMENT_LOCATE_LOCATECODE_LEN = 4;
uint64_t INSTRUMENT_LOCATE_COUNTRYCODE_LEN = 2;
uint64_t INSTRUMENT_LOCATE_CURRENCYCODE_LEN = 3;
uint64_t INSTRUMENT_LOCATE_MIC_LEN = 4;
uint64_t INSTRUMENT_LOCATE_PRODUCTTYPE_LEN = 1;
uint64_t INSTRUMENT_LOCATE_SYMBOLLENGTH_LEN = 1;

// 5. NBBO
uint64_t NBBO_INSTRUMENT_LOCATE_LEN = 4;
uint64_t NBBO_DEPTH_MARKET_CENTER_LEN = 2;
uint64_t NBBO_DEPTH_DENOMINATOR_LEN = 1;
uint64_t NBBO_FLAGS_LEN = 1;
uint64_t NBBO_SIDE_LEN = 1;
uint64_t NBBO_RFU_LEN = 1;

// 6. Trade
uint64_t TRADE_INSTRUMENT_LOCATE_LEN = 4;
uint64_t TRADE_MARKET_CENTER_LOCATE_LEN = 2;
uint64_t TRADE_TRADE_ID_LEN = 4;
uint64_t TRADE_PRICE_FLAGS_LEN = 1;
uint64_t TRADE_ELIGIBILITY_FLAGS_LEN = 1;
uint64_t TRADE_REPORT_FLAGS_LEN = 2;
uint64_t TRADE_CHANGE_FLAGS_LEN = 1;
uint64_t TRADE_CANCEL_FLAGS_LEN = 1;
uint64_t TRADE_DENOMINATOR_LEN = 1;

// 7. Instrument Value Update
uint64_t VALUE_UPDATE_INSTRUMENT_LOCATE_LEN = 4;
uint64_t VALUE_UPDATE_MARKET_CENTER_LOCATE_LEN = 2;
uint64_t VALUE_UPDATE_VALUE_UPDATE_FLAGS_LEN = 4;

// 8. Instrument Status
uint64_t INSTRUMENT_STATUS_INSTRUMENT_LOCATE_LEN = 4;
uint64_t INSTRUMENT_STATUS_MARKET_CENTER_LOCATE_LEN = 2;
uint64_t INSTRUMENT_STATUS_STATUS_TYPE_LEN = 1;
uint64_t INSTRUMENT_STATUS_STATUS_CODE_LEN = 1;
uint64_t INSTRUMENT_STATUS_REASON_CODE_LEN = 1;
uint64_t INSTRUMENT_STATUS_STATUS_FLAGS_LEN = 1;
uint64_t INSTRUMENT_STATUS_REASON_DETAIL_LENGTH_LEN = 1;

// 9. Channel Event
uint64_t CHANNEL_EVENT_INSTRUMENT_LOCATE_LEN = 4;
uint64_t CHANNEL_EVENT_MARKET_CENTER_LOCATE_LEN = 2;

// 10. Administrative Text
uint64_t ADMIN_TEXT_TEXT_LENGTH_LEN = 2;

// 10. Market Header
uint64_t MARKET_HEADER_MSG_TYPE_LEN = 1;
uint64_t MARKET_HEADER_PROTOCOLID_LEN = 1;
uint64_t MARKET_HEADER_CHANNEL_INDEX_LEN = 1;
uint64_t MARKET_HEADER_MESSAGE_FLAG_LEN = 1;
uint64_t MARKET_HEADER_UPSTREAM_SEQN_LEN = 4;
uint64_t MARKET_HEADER_UPSTREAM_NANOS_LEN = 4;
uint64_t MARKET_HEADER_TOTAL_LEN = 12;

// 11. Instruement Meta Data
uint64_t INSTRUMENT_META_DATA_MSG_TYPE_LEN = 1;
uint64_t INSTRUMENT_META_DATA_LOCATE_CODE_LEN = 4;

// 12. Option Delivery Component
uint64_t OPTION_DELIVERY_COMPONENT_MSG_TYPE_LEN = 1;
uint64_t OPTION_DELIVERY_COMPONENT_ROOT_CODE_LOCATE_LEN = 4;
uint64_t OPTION_DELIVERY_COMPONENT_COMPONENT_INDEX_LEN = 4;
uint64_t OPTION_DELIVERY_COMPONENT_COMPONENT_TOTAL_LEN = 4;
uint64_t OPTION_DELIVERY_COMPONENT_DELIVERABLE_UNITS_LEN = 4;
uint64_t OPTION_DELIVERY_COMPONENT_SETTLEMENT_METHOD_LEN = 1;
uint64_t OPTION_DELIVERY_COMPONENT_FIXED_AMOUNT_DENOMINATOR_LEN = 1;
uint64_t OPTION_DELIVERY_COMPONENT_FIXED_AMOUNT_NUMERATOR_LEN = 8;
uint64_t OPTION_DELIVERY_COMPONENT_CURRENCY_CODE_LEN = 3;
uint64_t OPTION_DELIVERY_COMPONENT_STRIKE_PERCENT_LEN = 2;
uint64_t OPTION_DELIVERY_COMPONENT_COMPONENT_SYMBOL_LOCATE_LEN = 4;

#endif